[profile.default]
# Directory / Directories that contain contracts to be analyzed
path = "./contracts"
# Optimizations that each contract will be analyzed for
optimizations = ['lib']
# Vulnerabilities that each contract will be analyzed for
vulnerabilities = ['']
# Vulnerabilities that each contract will be analyzed for
qa = ['']

